export interface Project {
  slug: string;
  title: string;
  tagline: string;
  status: 'Live' | 'In Progress' | 'Built';
  description: string;
  longDescription: string;
  problem: string;
  solution: string;
  techStack: string[];
  features: { icon: string; name: string; description: string }[];
  liveUrl: string | null;
  githubUrl: string;
  accentColor: string;
  category: string;
  year: string;
  challenges: string[];
  learnings: string[];
}

export const projects: Project[] = [
  {
    slug: 'isitai',
    title: 'IsItAI',
    tagline: 'Forensic AI image detection in the browser',
    status: 'Live',
    category: 'AI / Full-Stack',
    year: '2025',
    description: 'Five-layer forensic AI image detection — model ensembles, EXIF forensics, FFT analysis.',
    longDescription: 'IsItAI is a browser-based forensic detection system that determines whether an image was generated by AI. It runs five independent detection layers simultaneously and combines their confidence scores into a single verdict — without sending images to any external server.',
    problem: 'AI-generated images are flooding the internet. There was no fast, free, privacy-respecting tool that could reliably detect them without uploading your images to a third-party server.',
    solution: 'A five-layer forensic pipeline running entirely in the browser: model classification, EXIF metadata analysis, dimension heuristics, FFT frequency analysis, and face/skin texture analysis. Results in under 3 seconds.',
    techStack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'TensorFlow.js', 'Vercel'],
    features: [
      { icon: '🧠', name: 'Model Ensemble', description: 'Multiple AI classifiers vote on the result, reducing false positives dramatically.' },
      { icon: '📷', name: 'EXIF Forensics', description: 'Inspects metadata for AI generator signatures, software tags, and timestamp anomalies.' },
      { icon: '📐', name: 'Dimension Heuristics', description: 'AI images tend to have specific dimension ratios — this layer flags unusual combinations.' },
      { icon: '🌊', name: 'FFT Frequency Analysis', description: 'Analyses frequency domain patterns that reveal GAN generation artifacts invisible to the human eye.' },
      { icon: '👤', name: 'Face & Skin Analysis', description: 'Detects unnatural skin texture patterns and facial geometry inconsistencies common in AI portraits.' },
    ],
    liveUrl: 'https://isitai-gilt.vercel.app',
    githubUrl: 'https://github.com/Ali2191',
    accentColor: '#ef4444',
    challenges: [
      'Running TensorFlow.js models in the browser without blocking the UI thread required careful Web Worker orchestration.',
      'FFT analysis on large images was slow — implementing a downsampling strategy cut processing time by 70% with minimal accuracy loss.',
      'False positive rate was initially 30% on DSLR photos — solved by weighting the EXIF layer more heavily for images with rich metadata.',
    ],
    learnings: [
      'I would extract the detection pipeline into a proper API so the frontend stays thin and models can be updated independently.',
      'Progressive enhancement matters — showing partial results as each layer completes felt much better than waiting for all five.',
      'Browser APIs for image processing are more capable than I expected — the entire pipeline runs without any backend.',
    ],
  },
  {
    slug: 'learnify',
    title: 'Learnify',
    tagline: 'AI exam prep built for Pakistani students',
    status: 'In Progress',
    category: 'EdTech / Full-Stack',
    year: '2025',
    description: 'AI exam-prep platform targeting NUST NET, FAST NAT-ICS, MDCAT — adaptive practice + spaced repetition.',
    longDescription: 'Learnify is an AI-powered learning platform built specifically for Pakistani university entrance exams. It generates adaptive practice questions using Gemini API, tracks performance per topic, and uses spaced repetition to surface weak areas. Currently in active development.',
    problem: 'Pakistani students preparing for NUST NET, FAST NAT-ICS, and MDCAT have no modern, AI-powered study tool. Existing resources are PDFs and static MCQ banks — nothing adaptive, nothing personalized.',
    solution: 'A full-stack platform with Gemini-generated practice questions, per-topic performance tracking, spaced repetition scheduling, and a clean mobile-first UI. Students get a personalized study path, not a generic question bank.',
    techStack: ['Next.js 14', 'TypeScript', 'Supabase', 'Gemini API', 'Tailwind CSS', 'Vercel'],
    features: [
      { icon: '🤖', name: 'AI Question Generation', description: 'Gemini API generates fresh practice questions on demand, calibrated to exam difficulty.' },
      { icon: '📊', name: 'Performance Tracking', description: 'Per-topic accuracy tracked over time, surfacing weak areas automatically.' },
      { icon: '🔁', name: 'Spaced Repetition', description: 'SM-2 algorithm schedules question reviews at optimal intervals for long-term retention.' },
      { icon: '🇵🇰', name: 'Pakistan-Focused', description: 'Covers NUST NET, FAST NAT-ICS, MDCAT, and ECAT syllabi — topics local students actually need.' },
      { icon: '📱', name: 'Mobile-First', description: 'Designed for phones — most Pakistani students study on mobile, not desktop.' },
    ],
    liveUrl: null,
    githubUrl: 'https://github.com/Ali2191',
    accentColor: '#6366f1',
    challenges: [
      'Gemini API response quality varies — building a validation layer to reject malformed or off-syllabus questions was essential.',
      'Supabase Row Level Security setup for per-student data isolation took significant iteration to get right.',
      'The spaced repetition algorithm needed tuning — default SM-2 parameters were too aggressive for exam-style cramming.',
    ],
    learnings: [
      'I would implement a question caching layer earlier — regenerating questions each session is wasteful and slow.',
      'User onboarding matters enormously for EdTech — a 2-minute setup flow that asks about target exam and weak topics improved engagement significantly.',
      'Gemini prompting for educational content needs very specific constraints around difficulty level and answer format.',
    ],
  },
  {
    slug: 'resume-builder',
    title: 'Pakistan Resume Builder',
    tagline: 'AI-powered resumes built for the Pakistani job market',
    status: 'Built',
    category: 'AI / Productivity',
    year: '2024',
    description: 'ATS scoring, AI bullet writer, cover letter generator. Four templates for Pakistani job market.',
    longDescription: 'A full-stack resume builder with AI-powered features designed specifically for Pakistani job seekers. Most resume builders are built for Western job markets — this one understands local hiring norms, company types, and ATS systems used in Pakistan.',
    problem: 'Generic resume builders do not account for Pakistani hiring conventions, local company formats, or the ATS systems used by major Pakistani employers. Most AI resume tools also require expensive subscriptions.',
    solution: 'A free, full-stack resume builder with Claude-powered bullet writing, ATS scoring calibrated for Pakistani ATS systems, cover letter generation, and four templates matching local hiring manager expectations.',
    techStack: ['React', 'TypeScript', 'Claude API', 'PDF Generation', 'Tailwind CSS'],
    features: [
      { icon: '✍️', name: 'AI Bullet Writer', description: 'Describe what you did — Claude rewrites it as a strong, action-verb-led resume bullet.' },
      { icon: '🎯', name: 'ATS Scorer', description: 'Analyses resume against a job description and scores keyword match for Pakistani ATS systems.' },
      { icon: '📄', name: 'Cover Letter Generator', description: 'One-click cover letter generation personalised to job title and company.' },
      { icon: '🎨', name: 'Four Templates', description: 'Modern, Classic, Minimalist, and Corporate — all tuned for Pakistani hiring managers.' },
      { icon: '⬇️', name: 'PDF Export', description: 'High-fidelity PDF export that renders consistently across all browsers and printers.' },
    ],
    liveUrl: null,
    githubUrl: 'https://github.com/Ali2191',
    accentColor: '#10b981',
    challenges: [
      'PDF generation from React is notoriously inconsistent — settled on a headless browser approach for pixel-perfect output.',
      'Claude API prompt engineering for resume bullets required dozens of iterations to avoid generic output.',
      'ATS scoring is a heuristic, not a science — being transparent about this in the UI was important for user trust.',
    ],
    learnings: [
      'I would add a drag-and-drop section reordering earlier — users want to control section order from day one.',
      'Real-time ATS scoring as you type is a better UX than a score-on-submit model — reduces anxiety and encourages iteration.',
      'Claude works best for resume writing when given the job description AND the user\'s raw notes together in one prompt.',
    ],
  },
  {
    slug: 'unidash',
    title: 'UniDash',
    tagline: 'Unified productivity for students, in one mobile app',
    status: 'In Progress',
    category: 'Mobile / Productivity',
    year: '2025',
    description: 'Unified Gmail + Calendar + Tasks mobile app. React Native + Expo with Google OAuth.',
    longDescription: 'UniDash is a React Native app that brings Gmail, Google Calendar, and Google Tasks into a single, student-optimized interface. The goal is to eliminate the context switching that kills student productivity — one app, all the tools, optimised for how students actually work.',
    problem: 'Students juggle Gmail, Google Calendar, and Tasks across three separate apps. The context switching is a productivity killer — especially during exam season when every hour counts.',
    solution: 'A single React Native app with unified inbox, calendar, and task views. Google OAuth for seamless sign-in. A "Focus Mode" that surfaces only what matters today. Smart notifications that don\'t interrupt study sessions.',
    techStack: ['React Native', 'Expo', 'TypeScript', 'Google APIs', 'AsyncStorage', 'Expo Router'],
    features: [
      { icon: '📬', name: 'Unified Inbox', description: 'Gmail, Calendar events, and Tasks in one scrollable feed — sorted by what needs attention now.' },
      { icon: '🔐', name: 'Google OAuth', description: 'One-tap sign in with Google — no new account, no extra password.' },
      { icon: '🎯', name: 'Focus Mode', description: 'Surfaces only today\'s tasks and upcoming events — hides everything else.' },
      { icon: '📅', name: 'Smart Calendar', description: 'Month and week views with exam deadlines highlighted separately from regular events.' },
      { icon: '✅', name: 'Task Integration', description: 'Google Tasks synced in real time — check off tasks directly in the app.' },
    ],
    liveUrl: null,
    githubUrl: 'https://github.com/Ali2191',
    accentColor: '#f59e0b',
    challenges: [
      'Google APIs rate limiting required implementing a local cache layer — raw API calls on every render caused 429 errors quickly.',
      'Expo Router + Google OAuth required a custom deep-link handler for the OAuth callback on both iOS and Android.',
      'React Native\'s date/time handling is fragmented across platforms — a custom date utility layer was necessary for consistency.',
    ],
    learnings: [
      'I would use React Query from day one for all Google API calls — manual cache management is error-prone and verbose.',
      'Offline support should be a first-class feature, not an afterthought — students often study in areas with poor connectivity.',
      'Expo managed workflow is excellent until you need a native module — planning the bare workflow migration earlier would save time.',
    ],
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find(p => p.slug === slug);
}

export function getOtherProjects(slug: string): Project[] {
  return projects.filter(p => p.slug !== slug);
}
